MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: "D2SwinTransformer"
    DIVISIBILITY: 64
  SWIN:
    APE: False
    ATTN_DROP_RATE: 0.0
    DEPTHS: [2, 2, 18, 2]
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 192
    MLP_RATIO: 4.0
    NUM_HEADS: [6, 12, 24, 48]
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    PATCH_NORM: True
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 384
    QKV_BIAS: True
    QK_SCALE: None
    USE_CHECKPOINT: False
    WINDOW_SIZE: 12
    WEIGHTS: "swin_large_patch4_window12_384_22k.pkl"
  ENCODER:
    NAME: "MaskDINOEncoder"
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    COMMON_STRIDE: 4
    NUM_HEADS: 8
    NUM_LAYERS: 6
    NUM_CLASSES: 10
    NORM: "GN"
    DROPOUT: 0.0
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ 'res2', 'res3', 'res4', 'res5' ]
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    TOTAL_NUM_FEATURE_LEVELS: 4
    NUM_FEATURE_LEVELS: 4
    FEATURE_ORDER: low2high
  DECODER:
    NAME: "MaskDINODecoder"
    DIM_FEEDFORWARD: 2048
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 300
    NUM_CLASSES: 10
    DROPOUT: 0.0
    NUM_LAYERS: 9  # 9+1, 9 decoder layers, add one for the loss on learnable query
    ENFORCE_INPUT_PROJ: False
    DN: True
    DN_NOISE_SCALE: 0.4
    DN_NUM: 100
    TOTAL_NUM_FEATURE_LEVELS: 4

VERSION: 2
