training:
  lr: 0.00002
  lr_backbone_names: ['backbone.0']
  lr_backbone: 0.00002
  lr_linear_proj_names: ['reference_points', 'sampling_offsets']
  lr_linear_proj_mult: 0.1
  batch_size: 2
  weight_decay: 0.0001
  epochs: 10
  lr_drop: 8
  lr_drop_epochs: null
  clip_max_norm: 0.1
  sgd: false
  num_workers: 2

dataset:
  name: 'coco'
  path: '/home/dolphin/choi_ws/SatLaneDet_2024/dataset/soccer-players'
  num_classes: 20
  batch_size: 4
  image_height: 384
  image_width: 384
  train:
    augmentation: true
    coco_ann_file: 'instances_train.json'
  val:
    augmentation: false
    coco_ann_file: 'instances_val.json'
  test:
    augmentation: false
  augmentation:
    horizontal_flip:
      p: 0.5
    random_resized_crop:
      size: [384, 384]
      scale: [0.5, 1.0]
      ratio: [0.75, 1.333]
      p: 1.0
    random_brightness_contrast:
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5
    hue_saturation_value:
      hue_shift_limit: 20
      sat_shift_limit: 30
      val_shift_limit: 20
      p: 0.5
    random_gamma:
      gamma_limit: [80, 120]
      p: 0.5
    gauss_noise:
      std_range: [0.2, 0.44]
      mean_range: [0.0, 0.0]
      p: 0.5

backbone:
  type: 'SwinV2_384'  # 'ResNet50_Clip'
  output_layers: ['layer2', 'layer3', 'layer4']
  dilation: false
  position_embedding:
    type: 'sine'
    scale: 6.283185307179586  # 2 * pi

transformer:
  enc_layers: 6
  dec_layers: 6
  num_feature_levels: 4
  dim_feedforward: 1024
  hidden_dim: 256
  dropout: 0.1
  nheads: 8
  num_queries: 300
  dec_n_points: 4
  enc_n_points: 4
  with_box_refine: false
  aux_loss: true
  two_stage: true
  segmentation: false
  frozen_weights: false

matcher:
  class_cost: 2  # TODO check
  bbox_cost: 5
  giou_cost: 2

losses:
  cls_loss: 2
  bbox_loss: 5
  giou_loss: 2
  mask_loss: 1
  dice_loss: 1
  cardinality: true
  accuracy: true
  focal_alpha: 0.25

evaluation:
  topk: 100
  score_thresh: 0.1

runtime:
  output_dir: '/home/dolphin/choi_ws/SatLaneDet_2024/tblog'
  logger_name: 'defm_detr'
  device: 'cuda'
  seed: 42
  resume: ''
  start_epoch: 0
  eval: false
  cache_mode: false
