_BASE_: Base-COCO-InstanceSegmentation.yaml
DATASET:
  NAME: 'CustomDetectionDataset'
  ROOT_PATH: '/home/dolphin/choi_ws/SatLaneDet_2024/dataset/soccer-players'
  IMAGE_HEIGHT: 384
  IMAGE_WIDTH: 384
  TRAIN:
    SPLIT: 'train'
    AUGMENTATION: True
    BATCH_SIZE: 4
  VAL:
    SPLIT: 'val'
    AUGMENTATION: False
    BATCH_SIZE: 4
  TEST:
    SPLIT: 'test'
    AUGMENTATION: False
    BATCH_SIZE: 4
  AUGMENTATION:
    HorizontalFlip:
      p: 0.5
    RandomResizedCrop:
      size: [384, 384]
      scale: [0.5, 1.0]
      ratio: [0.75, 1.333]
      p: 0.5
    RandomBrightnessContrast:
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5
    HueSaturationValue:
      hue_shift_limit: 20
      sat_shift_limit: 30
      val_shift_limit: 20
      p: 0.5
    RandomGamma:
      gamma_limit: [80, 120]
      gamma_by_channels: True

MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: 'D2SwinTransformer'
    DIVISIBILITY: 64
  SWIN:
    APE: False
    ATTN_DROP_RATE: 0.0
    DEPTHS: [2, 2, 18, 2]
    DROP_PATH_RATE: 0.3
    DROP_RATE: 0.0
    EMBED_DIM: 192
    MLP_RATIO: 4.0
    NUM_HEADS: [6, 12, 24, 48]
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    PATCH_NORM: True
    PATCH_SIZE: 4
    PRETRAIN_IMG_SIZE: 384
    QKV_BIAS: True
    QK_SCALE: None
    USE_CHECKPOINT: False
    WINDOW_SIZE: 12
    WEIGHTS: 'swin_large_patch4_window12_384_22k.pkl'
  ENCODER:
    NAME: 'DINOEncoder'
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    COMMON_STRIDE: 4
    NUM_HEADS: 8
    NUM_LAYERS: 6
    NORM: 'GN'
    DROPOUT: 0.0
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: [ 'res2', 'res3', 'res4', 'res5' ]
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    TOTAL_NUM_FEATURE_LEVELS: 4
    NUM_FEATURE_LEVELS: 4
    FEATURE_ORDER: low2high
    ENFORCE_INPUT_PROJ: False
  DECODER:
    NAME: 'DINODecoder'
    DIM_FEEDFORWARD: 2048
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 300
    DROPOUT: 0.0
    NUM_LAYERS: 9  # 9+1, 9 decoder layers, add one for the loss on learnable query
    ENFORCE_INPUT_PROJ: False
    DN: True
    DN_NOISE_SCALE: 0.4
    DN_NUM: 100
    TOTAL_NUM_FEATURE_LEVELS: 4
    ENFORCE_INPUT_PROJ: False
  MATCHER:
    COST_TYPES: ['cls', 'box']  # ['cls', 'box', 'mask']
    COST_CLASS: 1
    COST_BOX: 1
    COST_GIOU: 1
    COST_MASK: 0
    COST_DICE: 0
    NUM_POINTS: 12_544  # 112*112
  DEC_HEAD:
    NUM_CLASSES: 10
  CRITERION:
    LOSS_TYPES: ['labels', 'boxes']  # ['labels', 'masks', 'boxes']
    CLASS_WEIGHT: 4.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    MASK_WEIGHT: 0.0
    DICE_WEIGHT: 0.0
    NUM_POINTS: 12_544  # 112*112
    NO_OBJECT_WEIGHT: 0.1
  TEST:
    OBJECT_MASK_THRESHOLD: 0.25,
    OVERLAP_THRESHOLD: 0.5,
    SEMANTIC_ON: False
    INSTANCE_ON: True

SOLVER:
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0

VERSION: 2
